export const FETCH_SERVICES = "FETCH_SERVICES";
export const FETCH_SERVICES_BEGIN = "FETCH_SERVICES_BEGIN";
export const FETCH_SERVICES_SUCCESS = "FETCH_SERVICES_SUCCESS";
export const FETCH_SERVICES_FAILED = "FETCH_SERVICES_FAILED";

export const FILTER_PROVIDERS = "FILTER_PROVIDERS";
export const FETCH_PROVIDERS = "FETCH_PROVIDERS";
export const FETCH_PROVIDERS_BEGIN = "FETCH_PROVIDERS_BEGIN";
export const FETCH_PROVIDERS_SUCCESS = "FETCH_PROVIDERS_SUCCESS";
export const FETCH_PROVIDERS_FAILED = "FETCH_PROVIDERS_FAILED";


